module.exports = {
  bk_events: require('./bk_events.model'),
  bk_layout_templates: require('./bk_layout_templates.model'),
  bk_template_objects: require('./bk_template_objects.model'),
  bk_event_layouts: require('./bk_event_layouts.model'),
  bk_event_layout_objects: require('./bk_event_layout_objects.model'),
  bk_event_table_types: require('./bk_event_table_types.model'),
  bk_event_tables: require('./bk_event_tables.model'),
  bk_users: require('./bk_users.model'),
  bk_sessions: require('./bk_sessions.model'),
  bk_login_limits: require('./bk_login_limits.model'),
  bk_bookings: require('./bk_bookings.model'),
  bk_booking_items: require('./bk_booking_items.model'),
  bk_table_assignments: require('./bk_table_assignments.model'),
  bk_payment_submissions: require('./bk_payment_submissions.model'),
  bk_waitlist_entries: require('./bk_waitlist_entries.model'),
  bk_check_ins: require('./bk_check_ins.model'),
  bk_files: require('./bk_files.model'),
  bk_audit_logs: require('./bk_audit_logs.model'),
};
